'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.42000
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System
Imports System.Runtime.Serialization

Namespace ServicoExposto
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="PacienteTO", [Namespace]:="http://tempuri.org/"),  _
     System.SerializableAttribute()>  _
    Partial Public Class PacienteTO
        Inherits Object
        Implements System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged
        
        <System.NonSerializedAttribute()>  _
        Private extensionDataField As System.Runtime.Serialization.ExtensionDataObject
        
        Private IdField As Integer
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomeField As String
        
        <System.Runtime.Serialization.OptionalFieldAttribute()>  _
        Private NomeMaeField As String
        
        Private NascimentoField As System.Nullable(Of Date)
        
        Private SexoField As ServicoExposto.SexoEnum
        
        <Global.System.ComponentModel.BrowsableAttribute(false)>  _
        Public Property ExtensionData() As System.Runtime.Serialization.ExtensionDataObject Implements System.Runtime.Serialization.IExtensibleDataObject.ExtensionData
            Get
                Return Me.extensionDataField
            End Get
            Set
                Me.extensionDataField = value
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true)>  _
        Public Property Id() As Integer
            Get
                Return Me.IdField
            End Get
            Set
                If (Me.IdField.Equals(value) <> true) Then
                    Me.IdField = value
                    Me.RaisePropertyChanged("Id")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property Nome() As String
            Get
                Return Me.NomeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomeField, value) <> true) Then
                    Me.NomeField = value
                    Me.RaisePropertyChanged("Nome")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false)>  _
        Public Property NomeMae() As String
            Get
                Return Me.NomeMaeField
            End Get
            Set
                If (Object.ReferenceEquals(Me.NomeMaeField, value) <> true) Then
                    Me.NomeMaeField = value
                    Me.RaisePropertyChanged("NomeMae")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=3)>  _
        Public Property Nascimento() As System.Nullable(Of Date)
            Get
                Return Me.NascimentoField
            End Get
            Set
                If (Me.NascimentoField.Equals(value) <> true) Then
                    Me.NascimentoField = value
                    Me.RaisePropertyChanged("Nascimento")
                End If
            End Set
        End Property
        
        <System.Runtime.Serialization.DataMemberAttribute(IsRequired:=true, Order:=4)>  _
        Public Property Sexo() As ServicoExposto.SexoEnum
            Get
                Return Me.SexoField
            End Get
            Set
                If (Me.SexoField.Equals(value) <> true) Then
                    Me.SexoField = value
                    Me.RaisePropertyChanged("Sexo")
                End If
            End Set
        End Property
        
        Public Event PropertyChanged As System.ComponentModel.PropertyChangedEventHandler Implements System.ComponentModel.INotifyPropertyChanged.PropertyChanged
        
        Protected Sub RaisePropertyChanged(ByVal propertyName As String)
            Dim propertyChanged As System.ComponentModel.PropertyChangedEventHandler = Me.PropertyChangedEvent
            If (Not (propertyChanged) Is Nothing) Then
                propertyChanged(Me, New System.ComponentModel.PropertyChangedEventArgs(propertyName))
            End If
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0"),  _
     System.Runtime.Serialization.DataContractAttribute(Name:="SexoEnum", [Namespace]:="http://tempuri.org/")>  _
    Public Enum SexoEnum As Integer
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Masculino = 0
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        Feminino = 1
        
        <System.Runtime.Serialization.EnumMemberAttribute()>  _
        NaoInformado = 2
    End Enum
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ServiceModel.ServiceContractAttribute(ConfigurationName:="ServicoExposto.ServicoSoap")>  _
    Public Interface ServicoSoap
        
        'CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorld(ByVal request As ServicoExposto.HelloWorldRequest) As ServicoExposto.HelloWorldResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/HelloWorld", ReplyAction:="*")>  _
        Function HelloWorldAsync(ByVal request As ServicoExposto.HelloWorldRequest) As System.Threading.Tasks.Task(Of ServicoExposto.HelloWorldResponse)
        
        'CODEGEN: Generating message contract since element name GetPacientesResult from namespace http://tempuri.org/ is not marked nillable
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetPacientes", ReplyAction:="*")>  _
        Function GetPacientes(ByVal request As ServicoExposto.GetPacientesRequest) As ServicoExposto.GetPacientesResponse
        
        <System.ServiceModel.OperationContractAttribute(Action:="http://tempuri.org/GetPacientes", ReplyAction:="*")>  _
        Function GetPacientesAsync(ByVal request As ServicoExposto.GetPacientesRequest) As System.Threading.Tasks.Task(Of ServicoExposto.GetPacientesResponse)
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorld", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicoExposto.HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicoExposto.HelloWorldRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class HelloWorldRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class HelloWorldResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="HelloWorldResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicoExposto.HelloWorldResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicoExposto.HelloWorldResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class HelloWorldResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public HelloWorldResult As String
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal HelloWorldResult As String)
            MyBase.New
            Me.HelloWorldResult = HelloWorldResult
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPacientesRequest
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPacientes", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicoExposto.GetPacientesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicoExposto.GetPacientesRequestBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute()>  _
    Partial Public Class GetPacientesRequestBody
        
        Public Sub New()
            MyBase.New
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.ServiceModel.MessageContractAttribute(IsWrapped:=false)>  _
    Partial Public Class GetPacientesResponse
        
        <System.ServiceModel.MessageBodyMemberAttribute(Name:="GetPacientesResponse", [Namespace]:="http://tempuri.org/", Order:=0)>  _
        Public Body As ServicoExposto.GetPacientesResponseBody
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal Body As ServicoExposto.GetPacientesResponseBody)
            MyBase.New
            Me.Body = Body
        End Sub
    End Class
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0"),  _
     System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced),  _
     System.Runtime.Serialization.DataContractAttribute([Namespace]:="http://tempuri.org/")>  _
    Partial Public Class GetPacientesResponseBody
        
        <System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue:=false, Order:=0)>  _
        Public GetPacientesResult() As ServicoExposto.PacienteTO
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal GetPacientesResult() As ServicoExposto.PacienteTO)
            MyBase.New
            Me.GetPacientesResult = GetPacientesResult
        End Sub
    End Class
    
    <System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Public Interface ServicoSoapChannel
        Inherits ServicoExposto.ServicoSoap, System.ServiceModel.IClientChannel
    End Interface
    
    <System.Diagnostics.DebuggerStepThroughAttribute(),  _
     System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")>  _
    Partial Public Class ServicoSoapClient
        Inherits System.ServiceModel.ClientBase(Of ServicoExposto.ServicoSoap)
        Implements ServicoExposto.ServicoSoap
        
        Public Sub New()
            MyBase.New
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String)
            MyBase.New(endpointConfigurationName)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As String)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal endpointConfigurationName As String, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(endpointConfigurationName, remoteAddress)
        End Sub
        
        Public Sub New(ByVal binding As System.ServiceModel.Channels.Binding, ByVal remoteAddress As System.ServiceModel.EndpointAddress)
            MyBase.New(binding, remoteAddress)
        End Sub
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoExposto_ServicoSoap_HelloWorld(ByVal request As ServicoExposto.HelloWorldRequest) As ServicoExposto.HelloWorldResponse Implements ServicoExposto.ServicoSoap.HelloWorld
            Return MyBase.Channel.HelloWorld(request)
        End Function
        
        Public Function HelloWorld() As String
            Dim inValue As ServicoExposto.HelloWorldRequest = New ServicoExposto.HelloWorldRequest()
            inValue.Body = New ServicoExposto.HelloWorldRequestBody()
            Dim retVal As ServicoExposto.HelloWorldResponse = CType(Me,ServicoExposto.ServicoSoap).HelloWorld(inValue)
            Return retVal.Body.HelloWorldResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoExposto_ServicoSoap_HelloWorldAsync(ByVal request As ServicoExposto.HelloWorldRequest) As System.Threading.Tasks.Task(Of ServicoExposto.HelloWorldResponse) Implements ServicoExposto.ServicoSoap.HelloWorldAsync
            Return MyBase.Channel.HelloWorldAsync(request)
        End Function
        
        Public Function HelloWorldAsync() As System.Threading.Tasks.Task(Of ServicoExposto.HelloWorldResponse)
            Dim inValue As ServicoExposto.HelloWorldRequest = New ServicoExposto.HelloWorldRequest()
            inValue.Body = New ServicoExposto.HelloWorldRequestBody()
            Return CType(Me,ServicoExposto.ServicoSoap).HelloWorldAsync(inValue)
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoExposto_ServicoSoap_GetPacientes(ByVal request As ServicoExposto.GetPacientesRequest) As ServicoExposto.GetPacientesResponse Implements ServicoExposto.ServicoSoap.GetPacientes
            Return MyBase.Channel.GetPacientes(request)
        End Function
        
        Public Function GetPacientes() As ServicoExposto.PacienteTO()
            Dim inValue As ServicoExposto.GetPacientesRequest = New ServicoExposto.GetPacientesRequest()
            inValue.Body = New ServicoExposto.GetPacientesRequestBody()
            Dim retVal As ServicoExposto.GetPacientesResponse = CType(Me,ServicoExposto.ServicoSoap).GetPacientes(inValue)
            Return retVal.Body.GetPacientesResult
        End Function
        
        <System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Function ServicoExposto_ServicoSoap_GetPacientesAsync(ByVal request As ServicoExposto.GetPacientesRequest) As System.Threading.Tasks.Task(Of ServicoExposto.GetPacientesResponse) Implements ServicoExposto.ServicoSoap.GetPacientesAsync
            Return MyBase.Channel.GetPacientesAsync(request)
        End Function
        
        Public Function GetPacientesAsync() As System.Threading.Tasks.Task(Of ServicoExposto.GetPacientesResponse)
            Dim inValue As ServicoExposto.GetPacientesRequest = New ServicoExposto.GetPacientesRequest()
            inValue.Body = New ServicoExposto.GetPacientesRequestBody()
            Return CType(Me,ServicoExposto.ServicoSoap).GetPacientesAsync(inValue)
        End Function
    End Class
End Namespace
