//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ArqSoftDotNet.WEB.ServicoExposto {
    using System.Runtime.Serialization;
    using System;
    
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="PacienteTO", Namespace="http://tempuri.org/")]
    [System.SerializableAttribute()]
    public partial class PacienteTO : object, System.Runtime.Serialization.IExtensibleDataObject, System.ComponentModel.INotifyPropertyChanged {
        
        [System.NonSerializedAttribute()]
        private System.Runtime.Serialization.ExtensionDataObject extensionDataField;
        
        private int IdField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeField;
        
        [System.Runtime.Serialization.OptionalFieldAttribute()]
        private string NomeMaeField;
        
        private System.Nullable<System.DateTime> NascimentoField;
        
        private ArqSoftDotNet.WEB.ServicoExposto.SexoEnum SexoField;
        
        [global::System.ComponentModel.BrowsableAttribute(false)]
        public System.Runtime.Serialization.ExtensionDataObject ExtensionData {
            get {
                return this.extensionDataField;
            }
            set {
                this.extensionDataField = value;
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true)]
        public int Id {
            get {
                return this.IdField;
            }
            set {
                if ((this.IdField.Equals(value) != true)) {
                    this.IdField = value;
                    this.RaisePropertyChanged("Id");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string Nome {
            get {
                return this.NomeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeField, value) != true)) {
                    this.NomeField = value;
                    this.RaisePropertyChanged("Nome");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false)]
        public string NomeMae {
            get {
                return this.NomeMaeField;
            }
            set {
                if ((object.ReferenceEquals(this.NomeMaeField, value) != true)) {
                    this.NomeMaeField = value;
                    this.RaisePropertyChanged("NomeMae");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=3)]
        public System.Nullable<System.DateTime> Nascimento {
            get {
                return this.NascimentoField;
            }
            set {
                if ((this.NascimentoField.Equals(value) != true)) {
                    this.NascimentoField = value;
                    this.RaisePropertyChanged("Nascimento");
                }
            }
        }
        
        [System.Runtime.Serialization.DataMemberAttribute(IsRequired=true, Order=4)]
        public ArqSoftDotNet.WEB.ServicoExposto.SexoEnum Sexo {
            get {
                return this.SexoField;
            }
            set {
                if ((this.SexoField.Equals(value) != true)) {
                    this.SexoField = value;
                    this.RaisePropertyChanged("Sexo");
                }
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Runtime.Serialization", "4.0.0.0")]
    [System.Runtime.Serialization.DataContractAttribute(Name="SexoEnum", Namespace="http://tempuri.org/")]
    public enum SexoEnum : int {
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Masculino = 0,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        Feminino = 1,
        
        [System.Runtime.Serialization.EnumMemberAttribute()]
        NaoInformado = 2,
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(ConfigurationName="ServicoExposto.ServicoSoap")]
    public interface ServicoSoap {
        
        // CODEGEN: Generating message contract since element name HelloWorldResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        ArqSoftDotNet.WEB.ServicoExposto.HelloWorldResponse HelloWorld(ArqSoftDotNet.WEB.ServicoExposto.HelloWorldRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/HelloWorld", ReplyAction="*")]
        System.Threading.Tasks.Task<ArqSoftDotNet.WEB.ServicoExposto.HelloWorldResponse> HelloWorldAsync(ArqSoftDotNet.WEB.ServicoExposto.HelloWorldRequest request);
        
        // CODEGEN: Generating message contract since element name GetPacientesResult from namespace http://tempuri.org/ is not marked nillable
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPacientes", ReplyAction="*")]
        ArqSoftDotNet.WEB.ServicoExposto.GetPacientesResponse GetPacientes(ArqSoftDotNet.WEB.ServicoExposto.GetPacientesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://tempuri.org/GetPacientes", ReplyAction="*")]
        System.Threading.Tasks.Task<ArqSoftDotNet.WEB.ServicoExposto.GetPacientesResponse> GetPacientesAsync(ArqSoftDotNet.WEB.ServicoExposto.GetPacientesRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorld", Namespace="http://tempuri.org/", Order=0)]
        public ArqSoftDotNet.WEB.ServicoExposto.HelloWorldRequestBody Body;
        
        public HelloWorldRequest() {
        }
        
        public HelloWorldRequest(ArqSoftDotNet.WEB.ServicoExposto.HelloWorldRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class HelloWorldRequestBody {
        
        public HelloWorldRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class HelloWorldResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="HelloWorldResponse", Namespace="http://tempuri.org/", Order=0)]
        public ArqSoftDotNet.WEB.ServicoExposto.HelloWorldResponseBody Body;
        
        public HelloWorldResponse() {
        }
        
        public HelloWorldResponse(ArqSoftDotNet.WEB.ServicoExposto.HelloWorldResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class HelloWorldResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public string HelloWorldResult;
        
        public HelloWorldResponseBody() {
        }
        
        public HelloWorldResponseBody(string HelloWorldResult) {
            this.HelloWorldResult = HelloWorldResult;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPacientesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPacientes", Namespace="http://tempuri.org/", Order=0)]
        public ArqSoftDotNet.WEB.ServicoExposto.GetPacientesRequestBody Body;
        
        public GetPacientesRequest() {
        }
        
        public GetPacientesRequest(ArqSoftDotNet.WEB.ServicoExposto.GetPacientesRequestBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute()]
    public partial class GetPacientesRequestBody {
        
        public GetPacientesRequestBody() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(IsWrapped=false)]
    public partial class GetPacientesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Name="GetPacientesResponse", Namespace="http://tempuri.org/", Order=0)]
        public ArqSoftDotNet.WEB.ServicoExposto.GetPacientesResponseBody Body;
        
        public GetPacientesResponse() {
        }
        
        public GetPacientesResponse(ArqSoftDotNet.WEB.ServicoExposto.GetPacientesResponseBody Body) {
            this.Body = Body;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.Runtime.Serialization.DataContractAttribute(Namespace="http://tempuri.org/")]
    public partial class GetPacientesResponseBody {
        
        [System.Runtime.Serialization.DataMemberAttribute(EmitDefaultValue=false, Order=0)]
        public ArqSoftDotNet.WEB.ServicoExposto.PacienteTO[] GetPacientesResult;
        
        public GetPacientesResponseBody() {
        }
        
        public GetPacientesResponseBody(ArqSoftDotNet.WEB.ServicoExposto.PacienteTO[] GetPacientesResult) {
            this.GetPacientesResult = GetPacientesResult;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ServicoSoapChannel : ArqSoftDotNet.WEB.ServicoExposto.ServicoSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ServicoSoapClient : System.ServiceModel.ClientBase<ArqSoftDotNet.WEB.ServicoExposto.ServicoSoap>, ArqSoftDotNet.WEB.ServicoExposto.ServicoSoap {
        
        public ServicoSoapClient() {
        }
        
        public ServicoSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ServicoSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ServicoSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArqSoftDotNet.WEB.ServicoExposto.HelloWorldResponse ArqSoftDotNet.WEB.ServicoExposto.ServicoSoap.HelloWorld(ArqSoftDotNet.WEB.ServicoExposto.HelloWorldRequest request) {
            return base.Channel.HelloWorld(request);
        }
        
        public string HelloWorld() {
            ArqSoftDotNet.WEB.ServicoExposto.HelloWorldRequest inValue = new ArqSoftDotNet.WEB.ServicoExposto.HelloWorldRequest();
            inValue.Body = new ArqSoftDotNet.WEB.ServicoExposto.HelloWorldRequestBody();
            ArqSoftDotNet.WEB.ServicoExposto.HelloWorldResponse retVal = ((ArqSoftDotNet.WEB.ServicoExposto.ServicoSoap)(this)).HelloWorld(inValue);
            return retVal.Body.HelloWorldResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArqSoftDotNet.WEB.ServicoExposto.HelloWorldResponse> ArqSoftDotNet.WEB.ServicoExposto.ServicoSoap.HelloWorldAsync(ArqSoftDotNet.WEB.ServicoExposto.HelloWorldRequest request) {
            return base.Channel.HelloWorldAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArqSoftDotNet.WEB.ServicoExposto.HelloWorldResponse> HelloWorldAsync() {
            ArqSoftDotNet.WEB.ServicoExposto.HelloWorldRequest inValue = new ArqSoftDotNet.WEB.ServicoExposto.HelloWorldRequest();
            inValue.Body = new ArqSoftDotNet.WEB.ServicoExposto.HelloWorldRequestBody();
            return ((ArqSoftDotNet.WEB.ServicoExposto.ServicoSoap)(this)).HelloWorldAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        ArqSoftDotNet.WEB.ServicoExposto.GetPacientesResponse ArqSoftDotNet.WEB.ServicoExposto.ServicoSoap.GetPacientes(ArqSoftDotNet.WEB.ServicoExposto.GetPacientesRequest request) {
            return base.Channel.GetPacientes(request);
        }
        
        public ArqSoftDotNet.WEB.ServicoExposto.PacienteTO[] GetPacientes() {
            ArqSoftDotNet.WEB.ServicoExposto.GetPacientesRequest inValue = new ArqSoftDotNet.WEB.ServicoExposto.GetPacientesRequest();
            inValue.Body = new ArqSoftDotNet.WEB.ServicoExposto.GetPacientesRequestBody();
            ArqSoftDotNet.WEB.ServicoExposto.GetPacientesResponse retVal = ((ArqSoftDotNet.WEB.ServicoExposto.ServicoSoap)(this)).GetPacientes(inValue);
            return retVal.Body.GetPacientesResult;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<ArqSoftDotNet.WEB.ServicoExposto.GetPacientesResponse> ArqSoftDotNet.WEB.ServicoExposto.ServicoSoap.GetPacientesAsync(ArqSoftDotNet.WEB.ServicoExposto.GetPacientesRequest request) {
            return base.Channel.GetPacientesAsync(request);
        }
        
        public System.Threading.Tasks.Task<ArqSoftDotNet.WEB.ServicoExposto.GetPacientesResponse> GetPacientesAsync() {
            ArqSoftDotNet.WEB.ServicoExposto.GetPacientesRequest inValue = new ArqSoftDotNet.WEB.ServicoExposto.GetPacientesRequest();
            inValue.Body = new ArqSoftDotNet.WEB.ServicoExposto.GetPacientesRequestBody();
            return ((ArqSoftDotNet.WEB.ServicoExposto.ServicoSoap)(this)).GetPacientesAsync(inValue);
        }
    }
}
